restaurant/config/routes.rb
Rails.application.routes.draw do
  scope '/account' do
    get '/confirm_email', to: 'users#confirm_email'
  end
  get '/edit_user_password', to: 'sessions#reset_password'
  patch '/edit_user_password', to: 'sessions#update_user_password'
  get '/reset_password', to: 'sessions#forgot_password'
  patch '/reset_password', to: 'sessions#reset_password_link'
  get '/signup', to: 'users#new'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  namespace :admin do
    resources :branches, :ingredients
    resources :inventories
  end
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :users
  root 'sessions#new', as: 'login_index', via: :all
end

restaurant/app/models/ingredient.rb
class Ingredient < ApplicationRecord

  # validation
  validates :name, :price, presence: true
  validate :validate_price, if: :price?
  validates :category, inclusion: [true, false]

  private
    def validate_price
      errors.add(:price, 'Should be positive') if price < 0
    end
end

restaurant/app/controllers/admin/ingredients_controller.rb
class Admin::IngredientsController < Admin::BaseController
  before_action :set_ingredient, only: [:destroy, :edit, :update]

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(permitted_params)
    if @ingredient.save
      redirect_with_flash("success", "ingredient_created", admin_ingredients_url)
    else
      render 'new'
    end
  end

  def index
    @ingredients = Ingredient.all
  end

  def update
    if @ingredient.update(permitted_params)
      redirect_with_flash("success", "successfully_saved", admin_ingredients_url)
    else
      render 'edit'
    end
  end

  def destroy
    redirect_with_flash("success", "successfully_destroyed", admin_ingredients_url) if @ingredient.destroy
  end

  private
    def permitted_params
      params.require(:ingredient).permit(:name, :price, :category, :extra_allowed)
    end

    def set_ingredient
      @ingredient = Ingredient.find_by(id: params[:id])
    end
end

restaurant/app/views/admin/ingredients/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel login-form">
      <div class="panel-heading text-center text-uppercase">
        Enter Ingredient Details
      </div>
      <%= render 'shared/errors', model: @ingredient %>
      <div class="panel-body">
        <%= form_for [:admin, @ingredient], html: { class: 'form-horizontal'} do |form| %>
          <div class="form-group">
            <div class="col-sm-12 form-label-group" data-id="form-label-group">
              <%= form.text_field :name, size: 40, class: 'form-control form-control-input', :'data-id'=>"form-control-input" %>
              <%= form.label :name, 'Enter ingredient name', class: "control-label", :'data-id'=>"control-label" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-12 form-label-group" data-id="form-label-group">
              <%= form.number_field :price, class: 'form-control form-control-input', :'data-id'=>"form-control-input" %>
              <%= form.label :price, 'Enter the price', class: "control-label", :'data-id'=>"control-label" %>
            </div>
          </div>
          <div class="form-group margin-bottom-0">
            <%= form.label :category_veg do %>
              <div class="col-sm-12">
                <%= form.radio_button :category, 0%>
                <span class="checkbox-label text-capitalize">Veg</span>
              </div>
            <% end %>
          </div>
          <div class="form-group margin-bottom-0">
            <%= form.label :category_nonveg do %>
              <div class="col-sm-12">
                <%= form.radio_button :category, 1%>
                <span class="checkbox-label text-capitalize">non Veg</span>
              </div>
            <% end %>
          </div>
          <div class="form-group">
            <%= form.label :extra_allowed do %>
              <div class="col-sm-12">
                <%= form.check_box :extra_allowed%>
                <span class="checkbox-label">Add extra Cheese</span>
              </div>
            <% end %>
          </div>
          <div class="form-group">
            <div class="col-sm-12">
              <%= submit_tag 'Continue', class: 'btn btn-danger btn-site-primary btn-lg btn-block text-uppercase' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

restaurant/app/views/admin/ingredients/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back', admin_ingredients_url, class: 'btn btn-danger btn-site-primary text-uppercase' %>

restaurant/app/views/admin/ingredients/index.html.erb
<%= link_to 'New Ingredient', new_admin_ingredient_url, class: 'btn btn-danger btn-site-primary text-uppercase' %>
<h1 class="text-center text-uppercase">Ingredients</h1>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Category</th>
      <th>Extra Allowed</th>
    </tr>
  </thead>
  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.price %></td>
        <% unless ingredient.category %>
          <td>Veg</td>
        <% else %>
          <td> Non-veg</td>
        <% end %>
        <td><%= ingredient.extra_allowed %></td>
        <td><%= link_to 'Edit', edit_admin_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', admin_ingredient_url(ingredient), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

restaurant/app/views/admin/ingredients/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', admin_ingredients_url, class: 'btn btn-danger btn-site-primary text-uppercase' %>