restaurant/config/routes.rb
Rails.application.routes.draw do
  scope '/account' do
    get '/confirm_email', to: 'users#confirm_email'
  end
  get '/edit_user_password', to: 'sessions#reset_password'
  patch '/edit_user_password', to: 'sessions#update_user_password'
  get '/reset_password', to: 'sessions#forgot_password'
  patch '/reset_password', to: 'sessions#reset_password_link'
  get '/signup', to: 'users#new'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  namespace :admin do
    resources :branches, :ingredients
    resources :inventories
  end
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :users
  root 'sessions#new', as: 'login_index', via: :all
end

restaurant/app/models/inventory.rb
class Inventory < ApplicationRecord
  # assosciations
  belongs_to :ingredient
  belongs_to :branch
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :comments

  # validations
  validates :branch_id, uniqueness: { scope: :ingredient_id }
  validates :quantity, presence: true
  validate :validate_quantity, if: :quantity?

  private
    def validate_quantity
      errors.add(:quantity, ' cannot be a negative number') if quantity < 0
    end
end

restaurant/app/controllers/admin/inventories_controller.rb
class Admin::InventoriesController < Admin::BaseController
  before_action :set_branch, only: [:index, :edit, :update]
  before_action :set_inventory, only: [:edit, :update]
  before_action :set_inventories, only: [:index]

  def index
    session[:current_location] = params[:branch] if params[:branch]
  end

  def edit
    set_comments
  end

  def update
    if @inventory.update(permitted_params)
      redirect_with_flash("success", "successfully_updated", admin_inventories_path(session[:current_location]))
    else
      set_comments
      render :edit
    end
  end

  private

    def set_inventory
      @inventory = Inventory.find_by(id: params[:id])
    end

    def set_inventories
      @inventories = Inventory.where(branch: @branch)
    end

    def set_branch
      if params[:branch]
        @branch = Branch.find_by(name: params[:branch])
      else
        @branch = Branch.find_by(name: session[:current_location])
      end
    end

    def permitted_params
      params.require(:inventory).permit(:quantity, comments_attributes: [:body, :user_id])
    end

    def set_comments
      @comments = @inventory.comments.includes(:user).limit(ENV["COMMENT_LIMIT"]).order(created_at: :desc)
    end
end

restaurant/app/views/admin/inventories/_comment.html.erb
<% comments.each do |comment| %>
  <div>
    <% if comment.persisted? %>
      <strong>
        <%= comment.user.name.titleize %> (<%= comment.created_at.to_s(:db) %>)
      </strong>
      <div>
        <%= comment.body %>
      </div>
    <% end %>
  </div>
<% end %>

restaurant/app/views/admin/inventories/_inventory.html.erb
<% inventories.each do |inventory| %>
  <tr>
    <td> <%= inventory.ingredient.name %> </td>
    <td> <%= inventory.quantity %> </td>
    <td><%= link_to 'Edit', edit_admin_inventory_path(inventory), class: 'btn btn-primary btn-xs' %></td>
  </tr>
<% end %>

restaurant/app/views/admin/inventories/edit.html.erb
<%= render 'shared/errors', model: @inventory %>
<strong> Location: <%= session[:current_location] %> </strong>
<br/>
<strong> Ingredient: <%= @inventory.ingredient.name %> </strong>
<br/>
<div>
  <%= form_for [:admin, @inventory], url: admin_inventory_path, html: { class: 'form-horizontal'} do |form| %>
    <div class='form-group'>
      <%= form.label :quantity, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= form.number_field :quantity, autofocus: true, required: true, placeholder: 'Enter quantity(add/reduce)', value: '',class: 'form-control' %>
      </div>
    <%= form.fields_for :comments, @inventory.comments.build do |form| %>
      <div class='form-group'>
        <%= form.label :body, 'Add Comment', class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= form.text_area :body, cols: '5', rows: '3', class: 'form-control', required: true %>
          <%= form.hidden_field :user_id, value: @current_user.id %>
        </div>
      </div>
    <% end %>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= form.submit 'Update Inventory', class: 'btn btn-primary btn-sm' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= link_to 'Back', admin_inventories_path(session[:current_location]), class: 'btn btn-info btn-sm back' %>
      </div>
    </div>
  <% end %>
</div>
<div class="comments">
  Previous comments
  <%= render partial: 'comment', locals: { comments: @comments } %>
</div>

restaurant/app/views/admin/inventories/index.html.erb
<strong> Location: <%= @branch.name %> </strong>
<table class="table table-hover stock">
  <thead>
    <tr>
      <th> Name </th>
      <th> Quantity </th>
      <th></th>
    </tr>
    <%= render partial: 'inventory', locals: { inventories: @inventories } %>
  </thead>
</table>