restaurant/config/routes.rb
Rails.application.routes.draw do
  scope '/account' do
    get '/confirm_email', to: 'users#confirm_email'
  end
  get '/edit_user_password', to: 'sessions#reset_password'
  patch '/edit_user_password', to: 'sessions#update_user_password'
  get '/reset_password', to: 'sessions#forgot_password'
  patch '/reset_password', to: 'sessions#reset_password_link'
  get '/signup', to: 'users#new'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  namespace :admin do
    resources :branches, :ingredients
    resources :inventories
  end
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :users
  root 'sessions#new', as: 'login_index', via: :all
end

restaurant/app/models/branch.rb
class Branch < ApplicationRecord
  # validations
  validates :name, :opening_time, :closing_time, presence: true
  validates :name, uniqueness: true
  validate :validate_timings, if: (:opening_time? && :closing_time?)

  # assosciations
  has_many :inventories, dependent: :destroy
  has_many :ingredients, through: :inventories

  def validate_timings
    errors.add(:opening_time, "should be before closing time") if closing_time < opening_time
  end
end

restaurant/app/controllers/admin/branches_controller.rb
class Admin::BranchesController < Admin::BaseController
  before_action :set_branch, only: [:destroy, :edit, :update]
  after_action :set_inventories, only: [:create]

  def new
    @branch = Branch.new
  end

  def create
    @branch = Branch.new(permitted_params)
    if @branch.save
      redirect_with_flash("success", "branch_created", admin_branches_url)
    else
      render 'new'
    end
  end

  def index
    @branches = Branch.all
  end

  def update
    if @branch.update(permitted_params)
      redirect_with_flash("success", "successfully_saved", admin_branches_url)
    else
      render 'edit'
    end
  end

  def destroy
    if @branch.destroy
      redirect_with_flash("success", "successfully_destroyed", admin_branches_url)
    else
      redirect_with_flash("danger", "error_destroy", admin_branches_url)
    end
  end

  private
    def permitted_params
      params.require(:branch).permit(:name, :opening_time, :closing_time)
    end

    def set_branch
      @branch = Branch.find_by(id: params[:id])
      redirect_with_flash("danger", "branch_not_found", admin_branches_url) unless @branch
    end

    def set_inventories
      Ingredient.all.each do |ingredient|
        @branch.inventories.build(ingredient_id: ingredient.id).save
      end
    end
end

restaurant/app/views/admin/branches/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel login-form">
      <div class="panel-heading text-center text-uppercase">
        Enter Restaurant Details
      </div>
      <%= render 'shared/errors', model: @branch %>
      <div class="panel-body">
        <%= form_for [:admin, @branch], html: { class: 'form-horizontal'} do |form| %>
          <div class="form-group">
            <div class="col-sm-12 form-label-group" data-id="form-label-group">
              <%= form.text_field :name, size: 40, class: 'form-control form-control-input', :'data-id'=>"form-control-input" %>
              <%= form.label :name, 'Enter branch name', class: "control-label", :'data-id'=>"control-label" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-12 form-label-group" data-id="form-label-group">
              <%= form.time_field :opening_time, size: 40, class: 'form-control form-control-input', :'data-id'=>"form-control-input" %>
              <%= form.label :opening_time, 'Enter opening time', class: "control-label", :'data-id'=>"control-label" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-12 form-label-group" data-id="form-label-group">
              <%= form.time_field :closing_time, size: 40, class: 'form-control form-control-input', :'data-id'=>"form-control-input" %>
              <%= form.label :closing_time, 'Enter closing time', class: "control-label", :'data-id'=>"control-label" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-12">
              <%= submit_tag 'Continue', class: 'btn btn-danger btn-site-primary btn-lg btn-block text-uppercase' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

restaurant/app/views/admin/branches/edit.html.erb
<h1>Update Branch</h1>
<%= link_to 'Back', admin_branches_url, class: 'btn btn-danger btn-site-primary text-uppercase pull-right' %>
<%= render 'form' %>

restaurant/app/views/admin/branches/index.html.erb
<h1 class="text-center text-uppercase">Branches</h1>
<div class="table-responsive margin-top-30">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Opening Time</th>
        <th>Closing Time</th>
      </tr>
    </thead>
    <tbody>
      <% @branches.each do |branch| %>
        <tr>
          <td><%= branch.name %></td>
          <td><%= branch.opening_time.strftime("%I:%M %p") %></td>
          <td><%= branch.closing_time.strftime("%I:%M %p") %></td>
          <td><%= link_to 'Edit', edit_admin_branch_path(branch),class: 'btn btn-danger btn-site-primary text-uppercase' %></td>
          <td><%= link_to 'Destroy', admin_branch_url(branch),class: 'btn btn-danger btn-site-primary text-uppercase' , method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to 'New Branch', new_admin_branch_url, class: 'btn btn-danger btn-site-primary text-uppercase'%>

restaurant/app/views/admin/branches/new.html.erb
<%= link_to 'Back', admin_branches_url, class: 'btn btn-danger btn-site-primary text-uppercase pull-right' %>
<%= render 'form' %>