restaurant/config/routes.rb
Rails.application.routes.draw do
  scope '/account' do
    get '/confirm_email', to: 'users#confirm_email'
  end
  get '/edit_user_password', to: 'sessions#reset_password'
  patch '/edit_user_password', to: 'sessions#update_user_password'
  get '/reset_password', to: 'sessions#forgot_password'
  patch '/reset_password', to: 'sessions#reset_password_link'
  get '/signup', to: 'users#new'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  namespace :admin do
    resources :branches, :ingredients
    resources :inventories
  end
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :users
  root 'sessions#new', as: 'login_index', via: :all
end

restaurant/app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand logo" href="#"><i>FoodZone</i></a>
    </div>
    <div class="collapse navbar-collapse" id="navigation">
      <ul class="nav navbar-nav navbar-right" id="navigation">
        <li class="links active"><%= link_to "Home", login_path %></li>
        <!-- <li class="links"><%= link_to "Help", login_path %></li> -->
        <% if @current_user %>
          <% if @current_user.role.eql? 'admin' %>
            <li class="links"><%= link_to "Branches", admin_branches_path %></li>
            <li class="links"><%= link_to "Ingredients", admin_ingredients_path %></li>
          <% end %>
          <li class="links"><%= link_to "Users", login_path %></li>
          <li class="dropdown links">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">My Account <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_user_path(@current_user) %></li>
              <li><%= link_to "Settings", edit_user_path(@current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
          </li>
          <% if @current_user.role.eql? 'admin' %>
            <li class="dropdown list-dropdown links">
              <%= form_tag admin_inventories_path, method: :get, class: 'locale' do %>
                <!-- <a class="dropdown-toggle" data-toggle="dropdown" href="#">Branches
                <span class="caret"></span></a> -->
                <!-- <ul class="dropdown-menu">
                  <li><a href="#">Page 1-1</a></li>
                  <li><a href="#">Page 1-2</a></li>
                  <li><a href="#">Page 1-3</a></li>
                </ul> -->
                <%= select_tag 'branch' , options_for_select(Branch.all.pluck('name'), session[:current_location]), onchange: 'this.form.submit()' %>
              <% end %>
            </li>
          <% end %>
        <% else %>
          <li class="dropdown links">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
              <span class="glyphicon glyphicon-user icon"></span></i><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Log In", login_path %></li>
              <li><%= link_to "Sign up", new_user_path %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

restaurant/app/views/layouts/_home-page.html.erb
<div class="container-fluid">
  <div class="row">
<!--     <div id="myCarousel" class="carousel slide margin-top-90" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag 'caraousel-img-1.jpg', :alt => 'Pizza', :class => 'carousel-image' %>
          <div class="carousel-caption">
            <h3>Yummy</h3>
            <p>Yummy</p>
          </div>
        </div>

        <div class="item">
          <%= image_tag 'caraousel-img-2.jpg', :alt => 'Pasta', :class => 'carousel-image' %>
          <div class="carousel-caption">
            <h3>Delicious</h3>
            <p>Lets have fun!</p>
          </div>
        </div>

        <div class="item">
          <%= image_tag 'caraousel-img-3.jpg', :alt => 'Raviolli', :class => 'carousel-image' %>
          <div class="carousel-caption">
            <h3>Delightful</h3>
            <p>Once and for all!</p>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div> -->
    <div class="primary-banner">
      <div class="banner">
        <div class="content text-center">
          <p class="logo">FoodZone</p>
          <p class="h3">Welcomes You</p>
          <p class="margin-top-30 lead">We introduce new cultures to visitors through interesting cuisines, offering a special dish for everyone regardless of their food preferences</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container section2">
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#all">All</a></li>
    <li><a data-toggle="tab" href="#veg">Veg</a></li>
    <li><a data-toggle="tab" href="#non-veg">Non-veg</a></li>
  </ul>

  <div class="tab-content">
    <div id="all" class="tab-pane fade in active">
      <h3>All</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      <div class="row">
        <div class="col-sm-4">
          <img src="https://www.tellusaboutus.com/comments/images/BK-WebComment/BB_WHOPPER-v1.png" class="img-responsive">
          <p class="description">Mac aloo tikki</p>
          <p class="price"></p>
        </div>
        <div class="col-sm-4">
          <img src="https://www.tellusaboutus.com/comments/images/BK-WebComment/BB_WHOPPER-v1.png" class="img-responsive">
        </div>
        <div class="col-sm-4">
          <img src="https://www.tellusaboutus.com/comments/images/BK-WebComment/BB_WHOPPER-v1.png" class="img-responsive">
        </div>
      </div>
<!--       <div class="row">
        <div class="col-sm-4">
          <img src="https://www.tellusaboutus.com/comments/images/BK-WebComment/BB_WHOPPER-v1.png" class="img-responsive">
        </div>
        <div class="col-sm-4">
          <img src="https://www.tellusaboutus.com/comments/images/BK-WebComment/BB_WHOPPER-v1.png" class="img-responsive">
        </div>
        <div class="col-sm-4">
          <img src="https://www.tellusaboutus.com/comments/images/BK-WebComment/BB_WHOPPER-v1.png" class="img-responsive">
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <img src="https://www.tellusaboutus.com/comments/images/BK-WebComment/BB_WHOPPER-v1.png" class="img-responsive">
        </div>
        <div class="col-sm-4">
          <img src="https://www.tellusaboutus.com/comments/images/BK-WebComment/BB_WHOPPER-v1.png" class="img-responsive">
        </div>
        <div class="col-sm-4">
          <img src="https://www.tellusaboutus.com/comments/images/BK-WebComment/BB_WHOPPER-v1.png" class="img-responsive">
        </div>
      </div> -->
    </div>
    <div id="veg" class="tab-pane fade">
      <h3>Veg</h3>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
    <div id="non-veg" class="tab-pane fade">
      <h3>Non-veg</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
    </div>
  </div>
</div>

restaurant/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/home-page' %>
    <div class="container-page container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>